services:
  mongodb:
    image: mongo
    container_name: beers_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  create-service:
    build: ./create-service
    container_name: create_service
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
    ports:
      - "8001:8080"

    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
