services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: [ "CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  create-service:
    build: ./create-service
    container_name: create_service
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
    ports:
      - "8080:8080"

    depends_on:
      mongodb:
        condition: service_healthy

  read-service:
    build: ./read-service
    container_name: read_service
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
    ports:
      - "8081:8081"

    depends_on:
      mongodb:
        condition: service_healthy

  update-service:
    build: ./update-service
    container_name: update_service
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
    ports:
      - "8082:8082"

    depends_on:
      mongodb:
        condition: service_healthy

  delete-service:
    build: ./delete-service
    container_name: delete_service
    environment:
      - MONGO_URI=${MONGO_URI}
      - DATABASE=${DATABASE}
      - COLLECTION=${COLLECTION}
    ports:
      - "8083:8083"

    depends_on:
      mongodb:
        condition: service_healthy

volumes:
  mongo_data:
