name: Create-Service CI/CD

on:
  push:
    paths:
      - "create-service/**"
  pull_request:
    paths:
      - "create-service/**"
  push:
    tags:
      - "v*.*.*"

jobs:
  tests:
    uses: ./.github/workflows/reusable-tests.yml
    with:
      working-directory: create-service

  docker:
    needs: tests
    uses: ./.github/workflows/reusable-docker.yml
    with:
      context: create-service
      dockerfile: create-service/Dockerfile
      image-name: create-service

  release:
    needs: docker
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/reusable-release.yml
