name: Create-Service CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"
      - "infra/**"
      - "assets/**"

  pull_request:
    branches:
      - main
    paths:
      - "create-service/**"

jobs:
  tests:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      working-directory: create-service

  docker:
    needs: tests
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/reusable-docker.yml
    with:
      context: create-service
      dockerfile: create-service/Dockerfile
      image-name: create-service

  release:
    needs: docker
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/reusable-release.yml
 