name: Delete-Service CI/CD

on:
  push:
    branches:
      - main
      - develop
    tags:
      - "v*.*.*"
    paths-ignore:
      - "**.md"
      - "infra/**"
      - "assets/**"

  pull_request:
    branches:
      - main
    paths:
      - "delete-service/**"

jobs:

  tests:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/reusable-tests.yml
    with:
      working-directory: delete-service

  docker:
    needs: tests
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    uses: ./.github/workflows/reusable-docker.yml
    with:
      context: delete-service
      dockerfile: delete-service/Dockerfile
      image-name: delete-service
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  release:
    needs: docker
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    uses: ./.github/workflows/reusable-release.yml
